project:
  type: website
  output-dir: docs

website:
  title: "Data to information ...."
  favicon: img/logos.jpg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - cv.qmd
      - publications.qmd
      - blog.qmd
      - software.qmd
      - posts.qmd
      - contact.qmd

format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full
    mainfont: Elms Sans
